# SPDX-License-Identifier: Apache-2.0

---
- name: copy the disk on target
  copy:
    src: "{{ disk_path }}"
    dest: "{{ vm_path }}/guest0.qcow2"
- name: "Create a first VM from template"
  cluster_vm:
    name: guest0
    command: create
    system_image: "{{ vm_path }}/guest0.qcow2"
    force: true
    enable: false
    xml: >-
      {{ lookup('template', xml_template,
      template_vars=dict(
        title='guest0',
        ovs_port='br0P0',
        cpuset=3,
        mac_address=hostvars["guest0"].mac_address,
        guest_image="{{ vm_path }}/guest0.qcow2"),
      errors='strict') }}
- name: copy the disk on target
  copy:
    remote_src: yes
    src: "{{ vm_path }}/guest0.qcow2"
    dest: "{{ vm_path }}/guest1.qcow2"
- name: "Create a second VM from template"
  cluster_vm:
    name: guest1
    command: create
    system_image: "{{ vm_path }}/guest1.qcow2"
    force: true
    enable: false
    xml: >-
      {{ lookup('template', xml_template,
      template_vars=dict(
        title='guest1',
        ovs_port='br0P1',
        cpuset=5,
        mac_address=hostvars["guest1"].mac_address,
        guest_image="{{ vm_path }}/guest1.qcow2"),
      errors='strict') }}
