# Copyright (C) 2019-2022 Savoir-faire Linux, Inc
# SPDX-License-Identifier: Apache-2.0

---
- name: Check if the .qcow2 has already been copied
  stat:
    path: "{{ vm_path }}/{{ vm_name }}.qcow2"
  register: disk_present

- name: copy the disk on target
  copy:
    src: "{{ disk_path }}"
    dest: "{{ vm_path }}/{{ vm_name }}.qcow2"
  when: not disk_present.stat.exists

- name: Copy template on target
  template:
    src: test.xml.j2
    dest: "/tmp/config_{{ vm_name }}.xml"

- name: Register if VM is defined
  shell: "virsh list --all | grep {{ vm_name }}"
  register: defined
  failed_when: false
  no_log: True

- name: Register if VM is running
  shell: "virsh list | grep {{ vm_name }}"
  register: running
  failed_when: false
  no_log: True
  when: defined.rc == 0 # Run if the VM exists

- name: stop {{ vm_name }}
  shell: "virsh destroy {{ vm_name }}"
  when: defined.rc ==0 and running.rc == 0

- name: remove {{ vm_name }}
  shell: >
    virsh managedsave-remove {{ vm_name }}
    && virsh undefine --nvram {{ vm_name }}
  when: defined.rc == 0

- name: define vm
  shell: virsh define /tmp/config_{{ vm_name }}.xml

- name: Remove template
  ansible.builtin.file:
    path: /tmp/config_{{ vm_name }}.xml
    state: absent

- name: Start {{ vm_name }}
  cluster_vm:
    name: "{{ vm_name }}"
    command: start
