# SPDX-License-Identifier: Apache-2.0

---
- name: Copy ptp4l service configuration file
  copy:
    dest: /etc/systemd/system/ptp4l.service
    src: ptp4l.service

- name: Copy phc2sys service configuration file
  template:
    dest: /etc/systemd/system/phc2sys.service
    src: phc2sys.service.j2

- name: Copy ptp4l configuration file
  template:
    dest: /etc/ptp4l.conf
    src: ptp4l.conf.j2

- name: Stop and disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no

- name: Start and enable ptp4l service
  systemd:
    name: ptp4l
    state: started
    enabled: yes

- name: Start and enable phc2sys service
  systemd:
    name: phc2sys
    state: started
    enabled: yes
