---
galaxy_info:
  author: "Anthony Ruhier"
  description: Configures systemd-networkd profiles
  license: BSD
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
dependencies: []
