# Copyright (C) 2019-2022 Savoir-faire Linux, Inc
# SPDX-License-Identifier: Apache-2.0

---
- name: Fetch host image
  hosts: jean
  tasks:

    - name: Fetch .gz host image
      fetch:
        src: >
          "{{ src_image_path }}/votp-host/
          seapath-host-bios-image-votp-host.wic.gz"
        dest: "{{ image_directory }}/host_bios/host-bios.wic.gz"
        flat: true

    - name: Fetch bmap host file
      fetch:
        src: >
          "{{ src_image_path }}/votp-host/
          seapath-host-bios-image-votp-host.wic.bmap"
        dest: "{{ image_directory }}//host_bios/host-bios.wic.bmap"
        flat: true
