# SPDX-License-Identifier: Apache-2.0

---
- name: Fetch guest image
  hosts: jean
  tasks:
    - name: Fetch .qcow2 guest image
      fetch:
        src: "{{ src_image_path }}/votp-guest/\
              seapath-guest-efi-dbg-image-votp-guest.wic.qcow2"
        dest: "{{ image_directory }}//guest_efi/guest-efi.qcow2"
        flat: yes
