# Copyright (C) 2019-2022 Savoir-faire Linux, Inc
# SPDX-License-Identifier: Apache-2.0

---
# This playbook configures the host's network,
# according to the variable "config"

- name: Setup host network
  hosts: hypervisors

  vars:
    # Config to apply
    # Either : dpdk, sriov, 2nd
    # Should be used to deploy different network configurations
    # on the same host, used by different VMs (DPDK/tap/SR-IOV)
    # But not yet fonctionnal
    config:
      - dpdk

    # Empty dictionnary to be able to append keys
    systemd_networkd_network: {}
    # PCI address of the interface used for SV reception
    nic: "0000:42:00.1"
    # Name of the interface used for SV reception
    interface: enp66s0f1

    # Optional : second network interface
    second_net:
      00-enp1s0:
        - Match:
            - Name: "enp1s0"
        - Network:
            - Address: "192.168.203.5"

  tasks:

    - name: Remove OVS config file
      file:
        path: /etc/ovs_configuration.json
        state: absent

    - name: Remove systemd-networkd config file
      shell:
        cmd: rm -f /etc/systemd/network/00-*
        warn: no

    # If not sriov
    - name: Set Network variable for classic OVS config
      set_fact:
        systemd_networkd_network:
          00-br0Host:
            - Match:
                - Name: "br0Host"
            - Network:
                - Address: "192.168.203.4"
      when: '"sriov" not in config'

    # If sriov
    - name: Set Network variable for SR-IOV config
      set_fact:
        systemd_networkd_network:
          00-sriov_interface:
            - Match:
                - Name: "{{ interface }}"
            - Network:
                - Address: "192.168.203.4"
      when: '"sriov" in config'

    # If 2nd network needed
    - name: Append value for the 2nd interface in the dict
      set_fact:
        systemd_networkd_network: >
          "{{ systemd_networkd_network | combine(second_net) }}"
      when: '"2nd" in config'

    - name: Create Network config
      import_role:
        name: systemd_networkd
    - name: Restart systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    - reboot:

    # If DPDK
    - name: Set OVS variable for DPDK config
      set_fact:
        ovs_bridges:
          - name: br0
            ports:
              - name: br0P0
                type: dpdkvhostuserclient
              - name: br0P1
                type: dpdkvhostuserclient
              - name: br0P2
                type: dpdkvhostuserclient
              - name: br0P3
                type: dpdkvhostuserclient
              - name: br0P4
                type: dpdkvhostuserclient
              - name: br0P5
                type: dpdkvhostuserclient
              - name: br0Host
                type: internal
              - name: br0External
                type: dpdk
                interface: "{{ nic }}"
      when: '"dpdk" in config'

    # If not DPDK
    - name: Set OVS variable for classic config
      set_fact:
        ovs_bridges:
          - name: br0
            ports:
              - name: br0P0
                type: tap
              - name: br0P1
                type: tap
              - name: br0P2
                type: tap
              - name: br0P3
                type: tap
              - name: br0P4
                type: tap
              - name: br0P5
                type: tap
              - name: br0Host
                type: internal
              - name: br0External
                type: system
                interface: "{{ interface }}"
      when: '"dpdk" not in config'

    # Apply OVS config
    - import_role:
        name: setup_ovs
      when: '"sriov" not in config'

    - reboot:
      when: need_reboot is defined and need_reboot
      # need_reboot defined in setup_ovs role
