# SPDX-License-Identifier: Apache-2.0

---
- name: Add PTP systemd services
  hosts: seapath
  tasks:
    - name: Copy ptp4l service configuration file
      copy:
        dest: /etc/systemd/system/ptp4l.service
        src: ../templates/ptp/ptp4l.service

    - name: Copy phc2sys service configuration file
      copy:
        dest: /etc/systemd/system/phc2sys.service
        src: ../templates/ptp/phc2sys.service

    - name: Copy ptp4l configuration file
      template:
        dest: /etc/ptp4l.conf
        src: ../templates/ptp/ptp4l.conf.j2

    - name: Stop and disable systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: no

    - name: Start and enable ptp4l service
      systemd:
        name: ptp4l
        state: started
        enabled: yes

    - name: Start and enable phc2sys service
      systemd:
        name: phc2sys
        state: started
        enabled: yes
