# SPDX-License-Identifier: Apache-2.0

---
- name: Remove all vms installed
  hosts: hypervisors
  tasks:

    - name: Stop VMs
      shell: "virsh destroy {{ hostvars[item].inventory_hostname }}"
      loop: "{{ groups['VMs'] }}"
      ignore_errors: true

    - name: Remove VMs
      shell: >
        "virsh managedsave-remove {{ hostvars[item].inventory_hostname }} &&
        virsh undefine --nvram {{ hostvars[item].inventory_hostname }}"
      loop: "{{ groups['VMs'] }}"
      ignore_errors: true

    - name: Remove disks
      shell:
        cmd: rm /var/lib/libvirt/images/*
        warn: false
        ignore_errors: true
